### ISSUE TITLE
Saves were not backed up

### ISSUE THREAD

**Issue by frostyplum** [dragos240/TownManager#2]
I tried to make a new town using TownManager, only to find my original town was nowhere to be found when I went to restore it. TownManager threw no exception and did nothing to alert me that it hadn't actually made a backup. I am livid. RIP town.

**Comment by Committee** [comment]
When you made the new town did you close acnl before going back to townanager or was it in a suspended state when you went to town manager?

**Comment by dragos240** [comment]
I'm really sorry you lost your town. Could you tell me if you are on the latest version of TownManager? The latest version has the "Clone town" and "Rename town" options. Also could you tell me if you are using the cartridge version of the game vs. the eShop/CIA version? Finally, I'll need to know if you are using the CIA or 3dsx version of TownManager. My best guess is you're using an outdated version of TownManager which might have caused this bug, but I need to confirm it's not a current issue.

**Comment by frostyplum** [comment]
First off sorry for the BM, I woke up in the middle of the night with a fever and losing my town was just too much for me to handle in that state T.T

It was not suspended, iirc I had just power cycled after an ntr plugin crashed and ACNL became unresponsive.

It was the CIA version of townmanager, and I downloaded ACNL through freeshop but I actually have a ticket for it that I purchased.

I thought it was the latest version but I feel dumb now for not checking sooner. I don't know which release it is, but I downloaded it through titleDB via FBI. I guess I learned my lesson there >.>

I realize this whole issue is sort of moot since it's an old release, but just to make sure something like this doesn't happen again, is there a way you can validate the backup after it has been created? Or has that already been implemented?

**Comment by dragos240** [comment]
Okay, so how long ago did you download it from TitleDB? Because it should look for the latest release in the "Releases" section and therefore it should be the latest version. I'm going to test this now to make sure it is the latest version, but it should be. If you downloaded it from TitleDB like... maybe a week ago or something, it wouldn't be the latest release because I had to contact the person who runs TitleDB to make it point to my github repo. Before release 1.0.0, TownManager did not support support the Amiibo update and it caused this problem. So it would make sense that this is an older release of TownManager. I'm going to start putting the version number in the title at the top of TownManager because it's good to know what version you have installed. Easier to diagnose issues and such.

**Comment by frostyplum** [comment]
(thought I had responded to this earlier, evidently you can't just respond to github emails in spite of what it said)

I’m fairly sure I downloaded it since you released a build supporting the amiibo update, but I wouldn't swear to it. I just remember seeing the update had released, and seeing TownManager for the first time, and then thinking I should wait for a build to address the update. Maybe it slipped my mind or something.

**Comment by dragos240** [comment]
Sorry to reopen this issue, but could you create another save file, back it up with JKSM, and, download the latest release of TownManager either from the "Releases" section or TitleDB? (shouldn't matter which). I would rather have you test this to make sure the issue is gone before this issue be closed. I'm fairly confident the issue is with an older release but I feel for you with the loss of your town and I don't want that to happen to anyone else :). I may be a developer, but I also play AC:NL and I would be very disappointed if my town were to be gone forever. Please respond if you are able and at your earliest convenience. Thanks.
